All correlations:
[{'Subjects': 50, 'Correlation': 0.9970840660662805}, {'Subjects': 100, 'Correlation': 0.9985214113356301}]
Correlations:
[{'Subjects': 50, 'Correlation': 0.9970840660662805}, {'Subjects': 100, 'Correlation': 0.9985214113356301}]
Averages:
          Correlation
Subjects             
50           0.997084
100          0.998521
Traceback (most recent call last):
  File "automated_subset_analysis.py", line 483, in <module>
    main()
  File "automated_subset_analysis.py", line 84, in main
    save_and_plot_correlations(n_vs_correls, cli_args)
  File "automated_subset_analysis.py", line 466, in save_and_plot_correlations
    all_plots.show(renderer="png")
  File "/usr/local/lib/python3.5/dist-packages/plotly/basedatatypes.py", line 2658, in show
    return pio.show(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/plotly/io/_renderers.py", line 376, in show
    bundle = renderers._build_mime_bundle(fig_dict, renderers_string=renderer, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/plotly/io/_renderers.py", line 282, in _build_mime_bundle
    renderer.activate()
  File "/usr/local/lib/python3.5/dist-packages/plotly/io/_base_renderers.py", line 125, in activate
    ensure_server()
  File "/usr/local/lib/python3.5/dist-packages/plotly/io/_orca.py", line 1344, in ensure_server
    validate_executable()
  File "/usr/local/lib/python3.5/dist-packages/plotly/io/_orca.py", line 1161, in validate_executable
    executable=" ".join(executable_list), help_result=help_result
ValueError: 
The orca executable is required in order to export figures as static images,
but the executable that was found at '/usr/bin/orca'
does not seem to be a valid plotly orca executable. Please refer to the end of
this message for details on what went wrong.

If you haven't installed orca yet, you can do so using conda as follows:

    $ conda install -c plotly plotly-orca

Alternatively, see other installation methods in the orca project README at
https://github.com/plotly/orca.

After installation is complete, no further configuration should be needed.

If you have installed orca, then for some reason plotly.py was unable to
locate it. In this case, set the `plotly.io.orca.config.executable`
property to the full path of your orca executable. For example:

    >>> plotly.io.orca.config.executable = '/path/to/orca'

After updating this executable property, try the export operation again.
If it is successful then you may want to save this configuration so that it
will be applied automatically in future sessions. You can do this as follows:

    >>> plotly.io.orca.config.save()

If you're still having trouble, feel free to ask for help on the forums at
https://community.plot.ly/c/api/python

The error encountered is that unexpected output was returned by the command
    $ /usr/bin/orca --help

b'Usage: orca [-h] [-v] [-r] [-s] [-t] [-l] [-e OPTION] [-d OPTION] [-p NAME]\n            [-u DIR] [--debug-file FILE] [--debug]\n\nOptional arguments:\n  -h, --help                   Show this help message and exit\n  -v, --version                3.18.2\n  -r, --replace                Replace a currently running instance of this\n                               screen reader\n  -s, --setup                  Set up user preferences (GUI version)\n  -t, --text-setup             Set up user preferences (text version)\n  -l, --list-apps              Print the known running applications\n  -e OPTION, --enable OPTION   Force use of option\n  -d OPTION, --disable OPTION  Prevent use of option\n  -p NAME, --profile NAME      Load profile\n  -u DIR, --user-prefs DIR     Use alternate directory for user preferences\n  --debug-file FILE            Send debug output to the specified file\n  --debug                      Send debug output to debug-YYYY-MM-DD-\n                               HH:MM:SS.out\n\nReport bugs to orca-list@gnome.org.\n'


